# Generated by Django 4.2.7 on 2024-05-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='apply_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
