# Generated by Django 4.2.7 on 2024-05-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('company', '0002_jobopening_apply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='apply_status',
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.canidate_register'),
        ),
    ]
